config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  get 'about', to: 'pages#about', as: :about
  get 'contact', to: 'pages#contact', as: :contact
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end

  def about

  end

  def contact
    @members = ["thanh", "dimitri", "germain", "damien", "julien"]

    if params[:member]
      @members = @members.select { |member| member.start_with?(params[:member]) }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>RailsIntro</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Our first about view 🚀</h1>
<%= link_to "Home page", root_path %>
<%= link_to "About", about_path %>
<%= link_to "Contact", contact_path %>

app/views/pages/contact.html.erb
<h1>CONTACT 🚀</h1>
<%= link_to "Home page", root_path %>
<%= link_to "About", about_path %>
<%= link_to "Contact", contact_path %>
<h1>Welcome to my Home page 🚀</h1>

<form action="/contact" method="get">
  <input type="text"
         value="<%= params[:member] %>"
         name="member"
         placeholder="Who are you looking for?">
  <input type="submit">
</form>

<h2>Meet our team</h2>
<ol>
  <% @members.each do |member| %>
    <li><%= member.capitalize %></li>
  <% end %>
</ol>

app/views/pages/home.html.erb
<h1>Welcome to my Home page 🚀</h1>
<button class="btn btn-primary">Click me</button>
<%= link_to "Home page", root_path %>
<%= link_to "About", about_path %>
<%= link_to "Contact", contact_path %>

<%= Time.now %>
<% %>

<h2>Meet our team</h2>
<ol>
  <li>Thanh</li>
  <li>Dimitri</li>
  <li>Germain</li>
  <li>Damien</li>
  <li>Julien</li>
</ol>